### ISSUE TITLE
富文本编辑器自定义高度无效

### ISSUE THREAD

**Issue by yangweijie** [Slowlyo/owl-admin-doc#4]
```
 public function form($isEdit = false): Form
    {
        return $this->baseForm()->body([
            amis()->RichTextControl('desc', '文本描述')->editorSetting(json_encode([
                'height'=>300,
            ],JSON_UNESCAPED_UNICODE)),
			amis()->RichTextControl('result', '结果'),
			amis()->TextControl('book_id', '所属书籍章节'),
        ]);
    }
```
![image](https://github.com/slowlyo/owl-admin-doc/assets/1614114/71003d50-f8ea-46a4-9742-8ed7dadb44c7)
高度为166px

**Comment by slowlyo** [comment]
该组件没有 editorSetting 这个属性, 好好看文档

**Comment by yangweijie** [comment]
![image](https://github.com/slowlyo/owl-admin-doc/assets/1614114/5f075b7f-ea04-406c-8a6e-5f6389c2c6c1)
![image](https://github.com/slowlyo/owl-admin-doc/assets/1614114/922ec823-bc60-4351-ac1d-6f8b1ed26ab8)
组件源码里明明有该方法，百度官方也支持的

 "slowlyo/owl-admin": "^3.5", 
官方的解析出来是对象，你组件配置是字符串 我改数组 传入也不行

**Comment by slowlyo** [comment]
所以  其实人家属性名叫options 不是么

**Comment by yangweijie** [comment]
> 所以 其实人家属性名叫options 不是么

是的，问题是设了options 编辑器高度无任何变化，不管弹窗还是新页面新增

```
 amis()->RichTextControl('desc', '文本描述')->options([
      'height'=>500,
      ]
  ),
```

**Comment by slowlyo** [comment]
![image](https://github.com/slowlyo/owl-admin-doc/assets/94038215/c0c31e3c-7d9b-4858-8a7c-dc98d8e9ac56)
![image](https://github.com/slowlyo/owl-admin-doc/assets/94038215/83ff3028-4274-4eb7-9a15-bd2cf07de49a)
![image](https://github.com/slowlyo/owl-admin-doc/assets/94038215/edf795ff-e4a2-4924-9aa2-07d6d29923fb)
